### ISSUE TITLE
LDAP connection errors in oxtrust and idp-process logs each time gluu-server24 service is started

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/community-edition-setup#73] opened 2015-12-23 16:55 UTC
Steps to reproduce:

1. Move into container and remove /opt/idp/logs/idp-process.log and /opt/tomcat/logs/oxtrust.log (to make it easier to analyze them after)
2. Move out of container and run "service gluu-server24 stop" command
3. Run "service gluu-server24 start" command

Result:

Service isn't accessible because a selection of vital components wasn't able to start. It seems all these components start trying to load their configuration from opendj too soon, when it still isn't ready to serve requests. If tomcat service is restarted from within the container after that all is working okay again.
Here are contents of [idp-process](https://github.com/GluuFederation/community-edition-setup/files/71040/srvc-start-idp-proc.txt) and [oxtrust](https://github.com/GluuFederation/community-edition-setup/files/71042/srvc-start-oxtrust.txt) logs when it happens.

In addition, even after tomcat's restart there is still one unclear LDAP connection error in the [oxtrust.log](https://github.com/GluuFederation/community-edition-setup/files/71043/srvc-start-oxtrust-after-restart.txt). Though it doesn't seem to affect any functionality.

**Comment by willow9886** [comment] 2016-02-09 18:55
@aliaksander-samuseu  If the error in the log file is resulting in broken features, then we care. If t's just an error in the log, it's annoying but we don't have time to deal with it..

**Comment by zamilskhan** [comment] 2016-04-26 21:29
This issue has been reported for 2.4.3. [Ticket link](https://support.gluu.org/installation/admin-portal-stops-working-after-restart-on-fresh-install-of-gluu-server-243-2672#at9997)

**Comment by yurem** [comment] 2016-04-27 12:30
@ganesh-at-wiw, @adrian-gluu I think it happens because tomcat start IDP quicker than OpenDJ start LDAP backends
It will be easy to reproduce in multi-core quick VM and probablu it exists in other CE versions too.
In gluu-script we need to add delay to check if LDAP service was started before running tomcat.

**Comment by aliaksander-samuseu** [comment] 2016-05-19 15:02
@yurem @adrian-gluu 

What is the status of it? One of our customers has just reported it again happening on his new 6.7 test instance.

**Comment by yurem** [comment] 2016-05-19 18:09
@aliaksander-samuseu if we run services manually are we getting this issue?

**Comment by mzico** [comment] 2016-05-23 10:15
@aliaksander-samuseu !

**Comment by nynymike** [comment] 2016-05-26 20:33
It may depend on the amount of data in the LDAP server, or the memory available to the particular instance, rather than the OS version.

**Comment by aliaksander-samuseu** [comment] 2016-05-26 20:56
@yurem 

Sorry, has just seen it. Not sure what do you mean by "manually". Issue is still the same as before - if you use "service gluu-server-2.4.3 start" from outside of the container - the issue happens. If you then move into the container and just restart tomcat - everything begins to work. So it's some sort of race condition that (it seems) has been fixed for other environments, but still happens in the CenOS 6.7 for some reason (not happens in 6.6 or 7.x , at the same time)

**Comment by aliaksander-samuseu** [comment] 2016-05-28 22:59
@yurem @nynymike @zamilskhan 

I've just been able to confirm a similar issue in our 2.4.2 package installed on CentOS7. Though in this case it doesn't happen all the time when you start service manually, but just sometimes. I can't see any patterns, it can start without issues several times in a row, then on next attempt fail to start with a lot of "couldn't create ldap pool"/"couldn't load oxauth configuration entry from LDAP" sort of errors in `wrapper.log`. Restart of tomcat from within the container always resolves, so it seems still the same case of race condition.

This particular vm has more than 6GB RAM.

**Comment by yurem** [comment] 2016-05-31 05:26
According to this we just run chroot with run level 3:
http://gitlab.gluu.org/root/gluu-ce-deb/blob/master/gluu-server.amd64/debian/gluu-server-2.4.3/etc/init.d/gluu-server-2.4.3#L73

We need to do:
1) review if after installing CE all services have right start/stop runlevel 3 order
2) update/fix setup to specify right order
3) check the same for all OS

I suspect systemd in CentOS 7/RHEL 7/etc can start our services in parallel. We need to find out how to start OpenDJ first

**Comment by ganesh-at-wiw** [comment] 2016-06-02 18:42
Yura is right. The problem is connected to the running order of the services inside chroot.
For that I did the following steps:
1. Logged into chroot.
2. The chkconfig lines should look like below:
```
GLUU.[root@vscrpr0001 ~]# grep chkconfig: /etc/init.d/{tomcat,opendj,httpd}
/etc/init.d/tomcat:# chkconfig: 2345 50 40
/etc/init.d/opendj:# chkconfig: 345 30 60
/etc/init.d/httpd:# chkconfig: - 70 20
GLUU.[root@vscrpr0001 ~]# 
```
3. Once this is done, we need to run the commands:
```
GLUU.[root@vscrpr0001 ~]# chkconfig tomcat on
GLUU.[root@vscrpr0001 ~]# chkconfig opendj on
GLUU.[root@vscrpr0001 ~]# chkconfig httpd on
GLUU.[root@vscrpr0001 ~]# 
```
4. Above commands will change the startup order of the services as below:
```
 GLUU.[root@vscrpr0001 ~]# ls /etc/rc.d/rc3.d/S*{tomcat,opendj,httpd}*
/etc/rc.d/rc3.d/S30opendj  /etc/rc.d/rc3.d/S50tomcat  /etc/rc.d/rc3.d/S70httpd
GLUU.[root@vscrpr0001 ~]# 
```

This output shows that the OpenDJ starts first at order 30, then Tomcat at order 50 and at last httpd at order 70. Numbers are arbitrary, but these suggest that lower the number, sooner the service will start.

**Comment by ganesh-at-wiw** [comment] 2016-06-02 18:46
After carrying out above steps, the startup opendj connection errors inside tomcat logs had vanished.

**Comment by mzico** [comment] 2016-06-02 18:48
@ganesh-at-wiw : do you think we can add this checks out of the box in 7.x?

**Comment by ganesh-at-wiw** [comment] 2016-06-02 18:52
I do not know yet @mzico . If errors are being encountered in 7.x also, then we can change order in 7.x too. But the above solution is for 6.x only and for CentOS and RHEL.

**Comment by adrian-gluu** [comment] 2016-06-02 21:56
This is something we need to set in setup.py before build the rpm it wont work check this output:
[root@pkg-rpm gluu-ce-rpm-243]# chroot gluu-
chroot: cannot change root directory to gluu-: No such file or directory
[root@pkg-rpm gluu-ce-rpm-243]# chroot gluu-server-2.4.3/
GLUU.[root@pkg-rpm /]# grep chkconfig: /etc/init.d/{tomcat,opendj,httpd}
grep: /etc/init.d/tomcat: No such file or directory
/etc/init.d/opendj:# chkconfig: 345 95 5
/etc/init.d/httpd:# chkconfig: - 85 15
GLUU.[root@pkg-rpm /]# chkconfig tomcat on
error reading information on service tomcat: No such file or directory
GLUU.[root@pkg-rpm /]# chkconfig opendj on
GLUU.[root@pkg-rpm /]# chkconfig httpd on
GLUU.[root@pkg-rpm /]# ls /etc/rc.d/rc3.d/S*{tomcat,opendj,httpd}*
ls: cannot access /etc/rc.d/rc3.d/S*tomcat*: No such file or directory
/etc/rc.d/rc3.d/S85httpd  /etc/rc.d/rc3.d/S95opendj
GLUU.[root@pkg-rpm /]# grep chkconfig: /etc/init.d/{tomcat,opendj,httpd}
grep: /etc/init.d/tomcat: No such file or directory
/etc/init.d/opendj:# chkconfig: 345 95 5
/etc/init.d/httpd:# chkconfig: - 85 15
GLUU.[root@pkg-rpm /]# chkconfig httpd off
GLUU.[root@pkg-rpm /]# grep chkconfig: /etc/init.d/{tomcat,opendj,httpd}
grep: /etc/init.d/tomcat: No such file or directory
/etc/init.d/opendj:# chkconfig: 345 95 5
/etc/init.d/httpd:# chkconfig: - 85 15
GLUU.[root@pkg-rpm /]# chkconfig opendj off
GLUU.[root@pkg-rpm /]# chkconfig opendj on
GLUU.[root@pkg-rpm /]# chkconfig httpd on
GLUU.[root@pkg-rpm /]# grep chkconfig: /etc/init.d/{tomcat,opendj,httpd}
grep: /etc/init.d/tomcat: No such file or directory
/etc/init.d/opendj:# chkconfig: 345 95 5
/etc/init.d/httpd:# chkconfig: - 85 15
GLUU.[root@pkg-rpm /]# ls /etc/rc.d/rc3.d/S*{tomcat,opendj,httpd}*
ls: cannot access /etc/rc.d/rc3.d/S*tomcat*: No such file or directory
/etc/rc.d/rc3.d/S85httpd  /etc/rc.d/rc3.d/S95opendj
GLUU.[root@pkg-rpm /]#

It didn't change the priority also tomcat is not set'ed yet because setup.py take care of that

**Comment by nynymike** [comment] 2016-06-07 15:24
Why is this issue outstanding for so long? This needs to be resolved ASAP.

**Comment by aliaksander-samuseu** [comment] 2016-06-09 18:15
@nynymike 
Ganesh prepared solution for this one, we tested it today and he said he is adding it to main branch.

**Comment by ganesh-at-wiw** [comment] 2016-06-09 21:01
I've committed the changes to separate branch and we'll test one rpm created out of this branch. If all works fine, we'll merge it in to master.

**Comment by ganesh-at-wiw** [comment] 2016-06-16 06:36
Changes merged to main branch and all seems well now.

**Closed by ganesh-at-wiw** 2016-06-16 06:36 UTC
Labels: bug
