### ISSUE TITLE
2.4.4 resolv.conf issue

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/community-edition-setup#255] opened 2017-01-19 21:44 UTC
The setup script `setup.py` changes the contents of the `/etc/resolv.con` file. When the package is installed, the contents of the host OS is used and it is changed after the setup script is run. The contents are reverted back after the Gluu Server `chroot` is stopped and restarted.

**Comment by mzico** [comment] 2017-01-19 21:46
@zamilskhan : how is 3.0.0 going with this thing? do we need to fix such in 3.0.0 as well?

**Comment by zamilskhan** [comment] 2017-01-19 22:09
The problem is only specific to 2.4.4. The problem is not there in 3.0.0. I will recheck with the latest package and post my findings. This is only specific to CentOS/RHEL systems.

**Comment by ganesh-at-wiw** [comment] 2017-01-20 05:43
Zamil, this is intended action. With every chroot start, the /etc/resolv.conf inside the chroot is copied from host /etc/resolv.conf.

**Comment by ganesh-at-wiw** [comment] 2017-01-20 05:57
Hi Zamil, this same action is repeated in 3.0.0 as well because this is not a bug.

**Comment by mzico** [comment] 2017-01-20 08:51
>> Zamil, this is intended action. With every chroot start, the /etc/resolv.conf inside the chroot is copied from host /etc/resolv.conf.

Does that mean if we have org specific nameserver entries in host resolv.conf file; upon reboot container's hosts would be intact and reflected correctly?

**Comment by ganesh-at-wiw** [comment] 2017-01-20 09:32
Yes, host copy will always be copied inside chroot.

**Comment by mzico** [comment] 2017-01-20 10:00
Thanks @ganesh-at-wiw 
We will do a quick test and inform you on status.

**Comment by zamilskhan** [comment] 2017-01-23 17:12
We could put a note asking the admin to restart the `chroot` after installation. This will help clear the situation with 2.4.4 `/etc/resolv.conf` file changing

**Comment by mzico** [comment] 2017-01-23 22:24
@zamilskhan  and @ganesh-at-wiw :

I tried locally with CentOS7.3+Gluu Server version: 2.4.4 SP1 and seems like even after reboot resolv.conf inside container was good. 
Here is a video I recorded, I showed Gluu Server version, status of resolv.conf inside and outside of container and rebooted server: https://youtu.be/7mm82MizefI

I think we just need to make sure if everything is working 3.0.0 now; after that we will be able to close the issue.

**Comment by ganesh-at-wiw** [comment] 2017-01-24 04:55
Yes Zico, that's what we've talked about that the copy from host to chroot is a feature not a bug.

**Comment by zamilskhan** [comment] 2017-01-24 15:17
@ganesh-at-wiw The query was about 2.4.4 which changes the contents of `/etc/resolv.con` file when the setup script is run. For all other following versions, there is no issue.

**Comment by yurem** [comment] 2017-02-27 12:04
Fixed

**Closed by yurem** 2017-02-27 12:04 UTC
