### ISSUE TITLE
GLuu 4.0 QA - passport service not starting

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/community-edition-setup#555] opened 2019-07-09 12:12 UTC
Issue: Passport service is not starting on fresh install, it seems startup script is broken

Error in logs
```
[root@autoqa ~]# systemctl status passport
● passport.service - Passport service
   Loaded: loaded (/usr/lib/systemd/system/passport.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Tue 2019-07-09 11:55:30 UTC; 3s ago
  Process: 17214 ExecStop=/opt/dist/scripts/passport stop (code=exited, status=0/SUCCESS)
  Process: 17188 ExecStart=/opt/dist/scripts/passport start (code=exited, status=0/SUCCESS)

Jul 09 11:55:30 autoqa.gluu.org systemd[1]: Starting Passport service...
Jul 09 11:55:30 autoqa.gluu.org passport[17188]: Starting passport:
Jul 09 11:55:30 autoqa.gluu.org passport[17188]: /opt/dist/scripts/passport: line 504: PORT=8090: command not found
Jul 09 11:55:30 autoqa.gluu.org passport[17188]: PID: [17209]
Jul 09 11:55:30 autoqa.gluu.org systemd[1]: Started Passport service.
```

**Comment by ganesh-at-wiw** [comment] 2019-07-09 16:41
@adrian-gluu The path /opt/dist/scripts/passport  does not exist which you adopted from /etc/init.d/passport. Please rectify this.

**Comment by nikdavnik** [comment] 2019-07-09 16:48
I checked in ubuntu18, /opt/dist/scripts/passport exits. The issue is comming from passport script itself. Please check error log above.
 /opt/dist/scripts/passport: line 504: PORT=8090: command not found

**Comment by aliaksander-samuseu** [comment] 2019-07-09 19:03
I've met it as well after switching to the latest from a previous 4.0 release which didn't have it

Few facts so far:

1. The command line it builds works, on itlself. I.e. if I just copy it to console and run, node starts. Here is example `PORT=8090 NODE_ENV=unknown NODE_CONFIG_DIR=/opt/gluu/node/passport/server HOSTNAME=localhost NODE_LOGGING_DIR=/opt/gluu/node/passport/server/logs /opt/node/bin/node --max-old-space-size=455 /opt/gluu/node/passport/server/app.js` - this starts node fine

2. When script tries to execute this very line, for some reason bash treats the env arguments preceding the executable as commands

3. Startup script in 4.0 is exactly the same as the one in 3.1.6 - and it starts ok in 3.1.6 instance on the same host. The only difference I see is that in 3.1.6 it’s started via script in `/etc/init.d/  dir (SysV "emulation"?) and in 4.0 it seems to use SysD directly.

**Comment by aliaksander-samuseu** [comment] 2019-07-10 00:07
@ganesh-at-wiw 

I've been able to find a solution by a chance. I don't understand the cause of it clearly, but after this modification service starts for me. May be it will give you an idea of what's going on.

Here is a diff which shows it:

```
# diff -c passport /opt/dist/scripts/passport
*** passport	2019-07-09 14:05:05.510429901 -0400
--- /opt/dist/scripts/passport	2019-07-09 19:57:17.474815746 -0400
***************
*** 501,507 ****
            			disown \$!
            			echo \$! > '$NODE_PID_FILE'"
        			else
!         			"${RUN_CMD[@]}" > /dev/null &
          			disown $!
          			echo $! > "$NODE_PID_FILE"
        			fi
--- 501,507 ----
            			disown \$!
            			echo \$! > '$NODE_PID_FILE'"
        			else
!         			/usr/bin/env ${RUN_CMD[@]} > /dev/null &
          			disown $!
          			echo $! > "$NODE_PID_FILE"
        			fi
```

**Comment by mbaser** [comment] 2019-07-10 09:11
> I checked in ubuntu18, /opt/dist/scripts/passport exits. The issue is comming from passport script itself. Please check error log above.
> /opt/dist/scripts/passport: line 504: PORT=8090: command not found

port 8090 is used by couchbase, I remembered I changed this port.

**Comment by nikdavnik** [comment] 2019-07-10 17:26
@sahiliamsso I generated new packages with fix. Please check and confirm

**Comment by ganesh-at-wiw** [comment] 2019-07-10 17:26
gluu-server-4.0_1-56~bionic+Ub18.04_amd64.deb works perfect. And @mbaser is right.

**Comment by ganesh-at-wiw** [comment] 2019-07-10 17:27
@sahiliamsso please see if you still face the problem.

**Comment by ganesh-at-wiw** [comment] 2019-07-10 19:01
https://github.com/GluuFederation/community-edition-setup/commit/f0057ff72369ab1a34f2f8781677d139e0ead34c#diff-34b91de3b6cf5b1fad78ef4a6b245b09

**Comment by sahiliamsso** [comment] 2019-07-11 22:06
Is it available in the new build yet?

**Comment by ganesh-at-wiw** [comment] 2019-07-15 18:25
@adrian-gluu @nikdavnik  has this been included in new build?

**Comment by willow9886** [comment] 2019-07-23 10:44
This has been fixed.

**Closed by willow9886** 2019-07-23 10:44 UTC
Labels: exclude from release notes
