### ISSUE TITLE
Could not start OpenLDAP from migration procedure

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/community-edition-setup#226] opened 2016-12-08 06:52 UTC
From **Procedure for replacing OpenDJ with OpenLDAP in 2.4.4.2** in https://github.com/GluuFederation/community-edition-setup/tree/openldap-migration/openldap_migration

Could not start OpenLDAP in step 5:

```
GLUU.root@v2442:~/community-edition-setup/openldap_migration# service solserver start
: not found/solserver: 14: /opt/symas/etc/openldap/symas-openldap.conf:
: not found/solserver: 22: /opt/symas/etc/openldap/symas-openldap.conf:
: not found/solserver: 32: /opt/symas/etc/openldap/symas-openldap.conf:
: not found/solserver: 38: /opt/symas/etc/openldap/symas-openldap.conf:
: not found/solserver: 48: /opt/symas/etc/openldap/symas-openldap.conf:
: not found/solserver: 54: /opt/symas/etc/openldap/symas-openldap.conf:
: not found/solserver: 59: /opt/symas/etc/openldap/symas-openldap.conf:
: not found/solserver: 65: /opt/symas/etc/openldap/symas-openldap.conf:
: not found/solserver: 70: /opt/symas/etc/openldap/symas-openldap.conf:
Symas OpenLDAP LDAP services slapd is not configured to run...  done.
GLUU.root@v2442:~/community-edition-setup/openldap_migration#
```

**Comment by uboznikov** [comment] 2016-12-08 07:02
![image](https://cloud.githubusercontent.com/assets/16329085/21000693/3f5d4454-bd57-11e6-8463-06738517df84.png)

**Comment by tecoholic** [comment] 2016-12-08 14:21
This is the first time this error has shown up. Check if the file `/opt/symas/etc/openldap/symas-openldap.conf` files exists and also report the OS you are running this on. The procedure has only been tested on a Ubuntu 14 system.

**Comment by uboznikov** [comment] 2016-12-08 14:34
![check](https://cloud.githubusercontent.com/assets/16329085/21013835/6c3f10c6-bd96-11e6-83cc-ba934acc7135.png)

**Comment by tecoholic** [comment] 2016-12-08 14:47
Does running `service solserver restart` help? Any errors? Kindly confirm Ubuntu 14.

**Comment by uboznikov** [comment] 2016-12-08 14:49
Same error with restart.

**Comment by tecoholic** [comment] 2016-12-08 14:50
Sorry I didn't notice the uname on the top.

**Comment by tecoholic** [comment] 2016-12-08 14:51
Ok I will see what's the issue, if I bump into this error. Until then, it is difficult to say if there is actually an error or just a one off occurance.

**Comment by tecoholic** [comment] 2016-12-09 17:19
After multiple instances of migration, I haven't been able to produce/encounter this bug. The only output I have seen repeatedly is 
```
GLUU.root@localhost:~/community-edition-setup/openldap_migration# service solserver start
Symas OpenLDAP LDAP services slapd starting...  done.
```

Maybe the issue is with the openldap package used for testing. Closing this issue now. Reopen if necessary.

**Closed by tecoholic** 2016-12-09 17:19 UTC
Labels: bug, High Priority
