### ISSUE TITLE
Some inconsistencies around picture URL

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/community-edition-setup#478] opened 2018-08-29 21:51 UTC
The attribute we are using to represent standard openid claim `picture` is supposed to be a URL, however `attributes.ldif` has `gluuAttributeType: binary` 

![pictattr](https://user-images.githubusercontent.com/5444180/44817637-b1782b00-abab-11e8-9b3d-d6580afe4448.png)

oxTrust should be able to interpret attributes values properly, ie. in case of a binary attribute, it should allow uploading a blob. Currently and happily, `picture` url shows a text box...

Finally, the default admin entry in CE has value `https://www.gluu.org/wp-content/themes/gluu/images/gl.png` but this does not exist, we should point somewhere else or remove ...

**Comment by mbaser** [comment] 2020-05-15 15:54
Duplicate of #656 and closed by https://github.com/GluuFederation/community-edition-setup/commit/24719520146eca99d5a062945eab8e0e4c1aa917

**Closed by mbaser** 2020-05-15 15:54 UTC
