### ISSUE TITLE
no listening sockets available, shutting down

### ISSUE THREAD

**Issue by jimscarver** [GluuFederation/community-edition-setup#58] opened 2015-09-05 17:08 UTC
We follow the setup which appears successful but nothing is listening on port 80, 8080 or 443.  apache is listening on port 8443.We are running CentOS 6.6 on Azure.

The only error we see in setup.log or setup_error.log is:

14:08:17 09/05/15 (99)Cannot assign requested address: make_sock: could not bind to address 40.76.89.82:80
no listening sockets available, shutting down
Unable to open logs

In apache wrapper.log we get one error a few times.

INFO   | jvm 2    | 2015/09/05 16:41:06 | Dynamic scope. Initialized successfully
INFO   | jvm 2    | 2015/09/05 16:41:20 | 2015-09-05 16:41:20,207 DEBUG [org.xdi.oxauth.service.AppInitializer] Created ldapAuthEntryManager1: org.gluu.site.ldap.persistence.LdapEntryManager@7c91266f
INFO   | jvm 2    | 2015/09/05 16:41:32 | 2015-09-05 16:41:32,639 DEBUG [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] Starting metadata validation
INFO   | jvm 2    | 2015/09/05 16:41:32 | 2015-09-05 16:41:32,644 DEBUG [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] Metadata validation finished
INFO   | jvm 2    | 2015/09/05 16:41:39 | org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.xdi.util.process.ProcessHelper.executeProgram(ProcessHelper.java:150)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.xdi.util.process.ProcessHelper.executeProgram(ProcessHelper.java:65)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.xdi.util.process.ProcessHelper.executeProgram(ProcessHelper.java:45)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.xdi.util.process.ProcessHelper.executeProgram(ProcessHelper.java:39)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.gluu.oxtrust.ldap.service.StatusCheckerTimer.runCheck(StatusCheckerTimer.java:189)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.gluu.oxtrust.ldap.service.StatusCheckerTimer.setCertificateExpiryAttributes(StatusCheckerTimer.java:163)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.gluu.oxtrust.ldap.service.StatusCheckerTimer.process(StatusCheckerTimer.java:126)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.gluu.oxtrust.ldap.service.StatusCheckerTimer.scheduleStatusChecking(StatusCheckerTimer.java:90)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.async.AsynchronousInterceptor.aroundInvoke(AsynchronousInterceptor.java:52)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.gluu.oxtrust.ldap.service.StatusCheckerTimer_$$_javassist_seam_7.scheduleStatusChecking(StatusCheckerTimer_$$_javassist_seam_7.java)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.util.Reflections.invokeAndWrap(Reflections.java:144)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.async.AsynchronousInvocation$1.process(AsynchronousInvocation.java:62)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.async.Asynchronous$ContextualAsynchronousRequest.run(Asynchronous.java:80)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.async.AsynchronousInvocation.execute(AsynchronousInvocation.java:44)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at org.jboss.seam.async.ThreadPoolDispatcher$RunnableAsynchronous.run(ThreadPoolDispatcher.java:142)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 2    | 2015/09/05 16:41:39 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 2    | 2015/09/05 16:41:39 | 2015-09-05 16:41:39,298 ERROR [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] There was an error executing command check_ssl
INFO   | jvm 2    | 2015/09/05 16:41:39 | 2015-09-05 16:41:39,298 ERROR [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] check_ssl retuned an unexpected result

opendj started successfully and I saw no errors in the logs.

I tried running a standard Apache on the machine and it works.  I do not know how to debug what is included in the gluu-install. Any advice would be much appreciated.

Thanks,

Jim

**Comment by mzico** [comment] 2015-09-05 17:15
Jim, 

We haven't tested Azure, so exactly not sure how it's handling the networking. Most probably the problem is related to IP_address which you used during installation of Gluu-Server.

**Comment by jimscarver** [comment] 2015-09-05 18:46
Thanks!  I has used the external IP address in the setup.  I tried again
with the internal IP address and it is now listening to port 80 and 443.

But now the connection times out.  I see this in the wrapper log:

INFO   | jvm 2    | 2015/09/05 18:15:38 | 2015-09-05 18:15:38,268 ERROR
[org.jboss.seam.async.AsynchronousExceptionHandler] Exception thrown whilst
executing asynchronous call
INFO   | jvm 2    | 2015/09/05 18:15:38 |
java.lang.ArrayIndexOutOfBoundsException: 1
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.gluu.oxtrust.ldap.service.StatusCheckerTimer.setCertificateExpiryAttributes(StatusCheckerTimer.java:165)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.gluu.oxtrust.ldap.service.StatusCheckerTimer.process(StatusCheckerTimer.java:126)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.gluu.oxtrust.ldap.service.StatusCheckerTimer.scheduleStatusChecking(StatusCheckerTimer.java:90)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.async.AsynchronousInterceptor.aroundInvoke(AsynchronousInterceptor.java:52)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.gluu.oxtrust.ldap.service.StatusCheckerTimer_$$_javassist_seam_7.scheduleStatusChecking(StatusCheckerTimer_$$_javassist_seam_7.java)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.util.Reflections.invokeAndWrap(Reflections.java:144)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.async.AsynchronousInvocation$1.process(AsynchronousInvocation.java:62)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.async.Asynchronous$ContextualAsynchronousRequest.run(Asynchronous.java:80)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.async.AsynchronousInvocation.execute(AsynchronousInvocation.java:44)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
org.jboss.seam.async.ThreadPoolDispatcher$RunnableAsynchronous.run(ThreadPoolDispatcher.java:142)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 2    | 2015/09/05 18:15:38 |       at
java.lang.Thread.run(Thread.java:745)
INFO   | jvm 2    | 2015/09/05 18:15:38 | 2015-09-05 18:15:38,415 DEBUG
[org.gluu.oxtrust.ldap.service.MetadataValidationTimer] Starting metadata
validation
INFO   | jvm 2    | 2015/09/05 18:15:38 | 2015-09-05 18:15:38,415 DEBUG
[org.gluu.oxtrust.ldap.service.MetadataValidationTimer] Metadata validation
finished
STATUS | wrapper  | 2015/09/05 18:15:51 | Pinging the JVM took 7 seconds to
respond.
STATUS | wrapper  | 2015/09/05 18:16:31 | Pinging the JVM took 10 seconds
to respond.

Any suggestion on a next step?

Thanks again,

Jim

**Comment by nynymike** [comment] 2015-09-05 18:49
This is not a bug, it is a deployment support request. I am closing the issue. Please register on https://support.gluu.org and re-post your problem if you really think its something we can help you with.  Also, at a high level, you need to manage the network, including routing, firewalls, and security. This varies from IAAS providers, and we don't know the ins and outs of each one.

**Closed by nynymike** 2015-09-05 18:49 UTC

**Comment by nynymike** [comment] 2015-09-11 00:27
Another customer recently reported a solution:

Azure assigns a public and private IP to the VM.   Initially the server could not be reached at the public address (404 - error) ... We modified the Apache VirtualHosts entries  to utilize `*:80` and `*:443` instead of setting directly  the Private (or Public IP address).   A second modification was also necessary.   Hosts file entries mapping the private IP address of the VM to the custom uri (idp.example.com) - we did this in \etc for both the gluu-server and the main.   I'm not (yet) an apache/tomcat guru but this was curious to me as there is already a DNS entry for the host [idp.example.com] pointing to the VMs public Ip address.  

Without the hosts entries, a 404 not found page would result even though Apache logs indicated it was seeing the inbound traffic - After the above changes were in place. the Gluu Server login page displayed correctly and admin login was achieved!   

We made one other discovery...  as Azure will assign new Public/Private Ip addresses each time the server is started. This was troublesome as manual editing of the hosts is necessary to change the private ip mapping in the hosts file ever time the VM was shutdown or rebooted... We rebuilt the VM from image and this time placed it into a Networking group which in turn allows setting a static private IP.

**Comment by jimscarver** [comment] 2015-09-11 11:15
Thanks Mike!

This does not account for the connection to the external ip timing out
which is like there is nothing listening on the public ip at all but
suggests issues we will need to address once we do have a connection.

I finally am able to connect locally but not from the outside. We may need
some azure support.  Port 443 is opened in the Azure panel.
[root@ce ~]# netstat -nl|grep 443
tcp        0      0 100.117.202.41:443          0.0.0.0:*
LISTEN
tcp        0      0 ::ffff:127.0.0.1:8443       :::*
 LISTEN

[root@ce ~]# curl -v --insecurehttps://ps1elmo.cloudapp.net
<https://www.google.com/url?q=https%3A%2F%2Fps1elmo.cloudapp.net&sa=D&sntz=1&usg=AFQjCNGEAK4QOBdwqCmykgppwDyZyBD-cA>
* About to connect() to ps1elmo.cloudapp.net port 443 (#0)
*   Trying 40.76.89.82... ^C^C
[root@ce ~]# curl -v --insecurehttps://100.117.202.41
<https://www.google.com/url?q=https%3A%2F%2F100.117.202.41&sa=D&sntz=1&usg=AFQjCNEIeoRMMbFJrPPOYdG8Sq7Pmb9Etw>
* About to connect() to 100.117.202.41 port 443 (#0)
*   Trying 100.117.202.41... connected
* Connected to 100.117.202.41 (100.117.202.41) port 443 (#0)
This redirects to /identity but there I get an empty page back which is a
separate issue.

I am waiting for my sysadmin to resolve the external connectivity issue to
see what I get in a browser.

I appreciate the info.

Thanks,

Jim

**Comment by nynymike** [comment] 2015-09-11 13:52
Gluu offers Community Edition Support: https://gluu.org/pricing 

If you want to engage a consultant, I think its just a network configuration issue that probably a contractor on https://upwork.com could probably resolve for you.  Why not switch to Digital Ocean?

**Comment by jimscarver** [comment] 2015-09-12 21:09
The gluu support pricing is a bit out of our league at present.

I do have a digital ocean host available and tried installing gluu there.  It says OK when I start gluu-server but it is not running.  I guess the problem is that it is running CentOS Linux release 7.1.1503.  I presume I need CentOS 6. :-(

**Comment by nynymike** [comment] 2015-09-12 21:23
Please register on https://support.gluu.org and post your support questions there. github is used for bugs or feature enhancements only.  

Yes, Centos 7 is defintely not supported. We plan to release Centos 7 / Redhat 7 very soon though.
