### ISSUE TITLE
No tomcat salt folder after running setup.py in Centos 6.5

### ISSUE THREAD

**Issue by shakaran** [GluuFederation/community-edition-setup#8] opened 2015-01-18 23:38 UTC
I get this log after running setup.py folder. I have setup nginx. I don't know if this script requires tomcat. If that the case, it should autodetect the binary presence of tomcat and warn the user about it.

	 cat setup.log 
	18:15:34 01/18/15 Installing Gluu Server
	18:15:34 01/18/15 ./setup.properties Properties not found. Interactive setup commencing...
	18:17:36 01/18/15 Checking properties
	18:17:47 01/18/15 Running: /bin/mkdir -p /etc/gluu/config
	18:17:47 01/18/15 Running: /bin/mkdir -p /etc/certs
	18:17:47 01/18/15 Running: /bin/mkdir -p /opt/gluu
	18:17:47 01/18/15 Running: /bin/mkdir -p /opt/gluu/bin
	18:17:47 01/18/15 Running: /bin/mkdir -p /home/tomcat/lib
	18:17:47 01/18/15 Running: /bin/mkdir -p /var/ox/photos
	18:17:47 01/18/15 Running: /bin/mkdir -p /var/ox/oxtrust/removed
	18:17:47 01/18/15 Error writing salt
	18:17:47 01/18/15 Traceback (most recent call last):
	  File "./setup.py", line 1023, in make_salt
		f = open("%s/conf/salt" % self.tomcatHome, 'w')
	IOError: [Errno 2] No such file or directory: '/opt/tomcat/conf/salt'

	18:17:47 01/18/15 ***** Error caught in main loop *****
	18:17:47 01/18/15 Traceback (most recent call last):
	  File "./setup.py", line 1442, in <module>
		installObject.make_salt()
	  File "./setup.py", line 1029, in make_salt
		sys.exit()
	SystemExit

**Comment by mzico** [comment] 2015-01-19 11:12
Hi Shakaran, 
Though I couldn't reproduce your problem but I saw a different problem in Gluu-Server-Repo-1.9-0.el6.x86_64.rpm. I am not able to log into oxTrust admin panel ( the GUI of Gluu Server ). 

I am exactly not sure but a quick question: possible for you to share why and where (inside Chroot container or outside chroot container ) you are trying in use nginx? Apahce is being configured and installed with CE installation... so... :) 

BTW, we are going to publish v2 of our Gluu Server Community Edition this week. So hopefully it will resolved your issue. 

Thanks for your bug report and testing. Please feel free to let us know if you see any issue anywhere, we will try our best to assist you. 

Kind regards, 
Zico

**Comment by yurem** [comment] 2015-02-25 15:47
Fixed in CE 2.0

**Closed by yurem** 2015-02-25 15:47 UTC
